import type { CommunicationTemplate, LifecycleCommandContract } from "@nexteam/core";
import { PORTAL_AUTHORIZATION_PROFILE_ID } from "../../../../../shared/lifecycle/policy.js";

export const QUOTE_ENGINE_COMMANDS: LifecycleCommandContract[] = [
  {
    commandId: "quote.send",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "quote.send",
    currentConditions: [{ code: "quote_ready", when: "draft quote has at least one valid line item and delivery target" }],
    dominantLabel: "Send quote",
    secondaryActions: ["Save draft", "Preview PDF"],
    requiredFields: ["deliveryMode"],
    blockingConditions: [{ code: "missing_required_field", when: "delivery destination missing", blockerCopy: "Add an email or text destination before sending this quote." }],
    transitionResult: "Moves quote_status from draft to sent.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "quote_sent" }, { kind: "audit", detail: "quote.sent" }],
    communicationTriggers: [{ templateId: "quote_sent", mode: "manual" }],
    auditEvent: "quote.sent",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Sending is online only." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "Retry-safe send keyed to quote and chosen delivery." },
    policyDependencies: ["D9"]
  },
  {
    commandId: "quote.revise",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "quote.revise",
    currentConditions: [{ code: "quote_editable", when: "quote is draft, sent, or change-requested but not accepted" }],
    dominantLabel: "Revise quote",
    secondaryActions: ["Renew quote", "Preview PDF"],
    requiredFields: ["lineItems"],
    blockingConditions: [{ code: "invalid_state", when: "quote already accepted", blockerCopy: "Accepted quotes stay immutable. Start follow-up work on the job instead." }],
    transitionResult: "Creates a new quote version, supersedes the prior version, and carries deposit math forward.",
    createdEntities: ["QuoteVersion"],
    sideEffects: [{ kind: "entity_create", detail: "quote.revision" }, { kind: "audit", detail: "quote.revised" }],
    communicationTriggers: [],
    auditEvent: "quote.revised",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Revision requires fresh totals and rule validation." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "One revision per client operation id." },
    policyDependencies: ["D5"]
  },
  {
    commandId: "quote.renew",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "quote.renew",
    currentConditions: [{ code: "quote_expired", when: "quote has expired but remains viewable" }],
    dominantLabel: "Renew quote",
    secondaryActions: ["Preview archived version"],
    requiredFields: ["newExpiryAt"],
    blockingConditions: [{ code: "invalid_state", when: "quote not expired", blockerCopy: "Only expired quotes can be renewed." }],
    transitionResult: "Resets expiry, rotates the approval token, keeps the same quote number, and archives the prior portal artifact.",
    createdEntities: ["QuoteVersionArchive"],
    sideEffects: [{ kind: "entity_update", detail: "quote.renew" }, { kind: "audit", detail: "quote.renewed" }],
    communicationTriggers: [],
    auditEvent: "quote.renewed",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Renewal is online only." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "Prevents duplicate renewals for the same request." },
    policyDependencies: ["D9"]
  },
  {
    commandId: "quote.archive",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "quote.send",
    currentConditions: [{ code: "quote_draft", when: "quote is a draft and has not entered approval, delivery, expiry, or renewal flow" }],
    dominantLabel: "Archive quote",
    secondaryActions: ["Save draft", "Preview PDF"],
    requiredFields: [],
    blockingConditions: [{ code: "invalid_state", when: "quote is not draft", blockerCopy: "Only draft quotes can be archived." }],
    transitionResult: "Moves quote_status from draft to archived while retaining the quote identity, number, and commercial history.",
    createdEntities: [],
    sideEffects: [{ kind: "entity_update", detail: "quote.archive" }, { kind: "audit", detail: "quote.archived" }],
    communicationTriggers: [],
    auditEvent: "quote.archived",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Archiving is online only." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "A quote can transition to archived only once from draft." },
    policyDependencies: []
  },
  {
    commandId: "portal.quote_view",
    type: "query",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "portal_granted", when: "tenant, customer, token, and resource grants all match" }],
    dominantLabel: "View quote",
    secondaryActions: ["Approve quote", "Request changes"],
    requiredFields: [],
    blockingConditions: [{ code: "authorization_missing", when: "portal token missing or expired", blockerCopy: "This quote link is no longer valid. Ask the service team for a fresh one." }],
    transitionResult: "Returns the current quote portal payload without mutating state.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "portal.quote_viewed" }],
    communicationTriggers: [],
    auditEvent: "portal.quote_viewed",
    confirmationTier: "none",
    offlineBehavior: { supported: false, behavior: "Portal access requires a live token check." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "portalToken"], description: "Read-only portal view scope." },
    policyDependencies: []
  },
  {
    commandId: "portal.quote_approve",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "deposit_not_required", when: "quote signature rules are satisfied and no deposit is required" }],
    dominantLabel: "Approve quote",
    secondaryActions: ["Request changes", "Decline"],
    requiredFields: ["customerName", "signature"],
    blockingConditions: [
      { code: "invalid_state", when: "quote expired", blockerCopy: "This quote expired and must be renewed before approval." },
      { code: "missing_required_field", when: "required signature missing", blockerCopy: "Add the required signature before approving." }
    ],
    transitionResult: "Creates QuoteAcceptance and moves quote_status to accepted.",
    createdEntities: ["QuoteAcceptance"],
    sideEffects: [{ kind: "entity_create", detail: "quote_acceptance.create" }, { kind: "communication", detail: "quote_approved" }, { kind: "audit", detail: "quote.approved" }],
    communicationTriggers: [{ templateId: "quote_approved", mode: "auto" }],
    auditEvent: "quote.approved",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Client approval requires a live portal token." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "Only one acceptance record per client approval attempt." },
    policyDependencies: ["D1"]
  },
  {
    commandId: "portal.quote_approve_and_pay_deposit",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "deposit_required", when: "signature, deposit, and card-on-file rules all apply together" }],
    dominantLabel: "Approve and pay deposit",
    secondaryActions: ["Request changes", "Decline"],
    requiredFields: ["customerName", "signature", "paymentMethod"],
    blockingConditions: [
      { code: "invalid_state", when: "quote expired", blockerCopy: "This quote expired and must be renewed before approval." },
      { code: "missing_required_field", when: "deposit payment details missing", blockerCopy: "Add the required deposit payment details before approving." }
    ],
    transitionResult: "On success creates QuoteAcceptance plus a fully allocated deposit payment; on failure leaves quote_status as sent and records the failed attempt.",
    createdEntities: ["QuoteAcceptance", "Payment", "Allocation"],
    sideEffects: [
      { kind: "payment_attempt", detail: "deposit.collect_atomic" },
      { kind: "communication", detail: "quote_approved|deposit_failure" },
      { kind: "audit", detail: "quote.approval_attempted" }
    ],
    communicationTriggers: [{ templateId: "quote_approved", mode: "auto" }, { templateId: "deposit_failure", mode: "auto" }],
    auditEvent: "quote.approval_attempted",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Portal deposit collection is online only." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "Ties the atomic approval-plus-deposit attempt to one portal action." },
    policyDependencies: ["D1", "D4", "D5"]
  },
  {
    commandId: "portal.quote_decline",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "quote_sent", when: "customer is responding to a sent quote" }],
    dominantLabel: "Decline quote",
    secondaryActions: ["Request changes"],
    requiredFields: ["reason"],
    blockingConditions: [{ code: "invalid_state", when: "quote already accepted", blockerCopy: "This quote is already accepted and can no longer be declined." }],
    transitionResult: "Moves quote_status to declined and records the customer reason.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "quote.declined" }],
    communicationTriggers: [],
    auditEvent: "quote.declined",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Portal response requires live token validation." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "One decline decision per portal submit." },
    policyDependencies: []
  },
  {
    commandId: "portal.quote_request_changes",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "quote_sent", when: "customer wants changes without declining the quote outright" }],
    dominantLabel: "Request changes",
    secondaryActions: ["Decline quote"],
    requiredFields: ["message"],
    blockingConditions: [{ code: "invalid_state", when: "quote already accepted", blockerCopy: "Accepted quotes stay locked. New changes belong on the job." }],
    transitionResult: "Sets client_response_status to changes_requested while leaving quote_status unchanged.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "quote.change_requested" }],
    communicationTriggers: [],
    auditEvent: "quote.change_requested",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Portal response requires live token validation." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "One change request per portal submit." },
    policyDependencies: []
  },
  {
    commandId: "quote.internal_approve",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "quote.send",
    currentConditions: [{ code: "staff_manual_override", when: "internal staff is approving verbally or manually" }],
    dominantLabel: "Approve internally",
    secondaryActions: ["Send quote"],
    requiredFields: ["approverName", "approvalReason"],
    blockingConditions: [{ code: "invalid_state", when: "quote expired", blockerCopy: "Renew the quote before approving it internally." }],
    transitionResult: "Marks the quote accepted through the internal-manual path while keeping deposit collection as a separate later action if needed.",
    createdEntities: ["QuoteAcceptance"],
    sideEffects: [{ kind: "entity_create", detail: "quote_acceptance.create_internal" }, { kind: "audit", detail: "quote.approved_internal" }],
    communicationTriggers: [],
    auditEvent: "quote.approved_internal",
    confirmationTier: "high",
    offlineBehavior: { supported: false, behavior: "Approval must validate the current quote version online." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "Prevents duplicate internal approval writes." },
    policyDependencies: ["D1"]
  }
];

export const QUOTE_ENGINE_COMMUNICATIONS: CommunicationTemplate[] = [
  {
    templateId: "quote_sent",
    trigger: "quote.send",
    channels: ["email", "sms"],
    mode: "manual",
    recipientResolution: "Resolve to the quote's delivery selection, then fall back to the client correspondence contact.",
    previewRequired: true,
    suppressionRule: "Suppress only when the selected delivery target is missing or the contact has opted out of that channel.",
    idempotencyScope: "quote.send:{quoteId}:{deliveryMode}:{quoteVersion}",
    failureBehavior: "Leave quote sent state intact, create a delivery failure attention item, and expose retry.",
    auditEvent: "quote.sent",
    attachmentPolicy: "Attach the current immutable quote PDF only."
  },
  {
    templateId: "quote_approved",
    trigger: "portal.quote_approve",
    channels: ["email"],
    mode: "auto",
    recipientResolution: "Send to the approving customer email and copy the tenant reply-to address.",
    previewRequired: false,
    suppressionRule: "Skip only if the client has no deliverable email on file.",
    idempotencyScope: "quote.approved:{quoteId}:{quoteVersion}:{acceptanceId}",
    failureBehavior: "Leave acceptance intact, log failure, and queue an internal follow-up.",
    auditEvent: "quote.approval_confirmation_sent",
    attachmentPolicy: "Attach the approved quote PDF and any deposit receipt that exists."
  },
  {
    templateId: "deposit_failure",
    trigger: "portal.quote_approve_and_pay_deposit.failure",
    channels: ["email"],
    mode: "auto",
    recipientResolution: "Use the same email that attempted the portal approval.",
    previewRequired: false,
    suppressionRule: "Never suppress when the quote requires a deposit and the customer has an email address.",
    idempotencyScope: "quote.deposit_failure:{quoteId}:{attemptId}",
    failureBehavior: "Create an internal attention item if delivery also fails.",
    auditEvent: "quote.deposit_failure_notified",
    attachmentPolicy: "No attachments."
  }
];
