import type { CommunicationTemplate, LifecycleCommandContract } from "@nexteam/core";
import { PORTAL_AUTHORIZATION_PROFILE_ID } from "../../../../../../../crm/lifecyclePolicy.js";

export const REQUEST_CORE_COMMANDS: LifecycleCommandContract[] = [
  {
    commandId: "request.contact",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "request.contact",
    currentConditions: [{ code: "request_open", when: "request has not been closed or converted" }],
    dominantLabel: "Log contact attempt",
    secondaryActions: ["Schedule follow-up", "Convert to quote", "Flag for manager review"],
    requiredFields: ["channel", "outcome"],
    blockingConditions: [],
    transitionResult: "Creates ContactInteraction and may move request_status to contact_attempted or awaiting_customer_info.",
    createdEntities: ["ContactInteraction"],
    sideEffects: [{ kind: "audit", detail: "request.contact.logged" }],
    communicationTriggers: [],
    auditEvent: "request.contact.logged",
    confirmationTier: "none",
    offlineBehavior: { supported: false, behavior: "Office-only action; requires live data." },
    idempotencyScope: { keys: ["tenantId", "requestId", "clientOperationId"], description: "Avoid duplicate contact interactions from retries." },
    policyDependencies: []
  },
  {
    commandId: "request.convert_to_job",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "request.convert_to_job",
    currentConditions: [{ code: "path_a_ready", when: "pricing locked, in service area, intake complete, and no custom scope required" }],
    dominantLabel: "Create job",
    secondaryActions: ["Create quote", "Mark not serviceable"],
    requiredFields: ["clientId", "intakeSnapshot"],
    blockingConditions: [{ code: "missing_required_field", when: "intake is incomplete", blockerCopy: "Finish the intake details before creating a job." }],
    transitionResult: "Creates a linked draft job shell and moves the request toward qualified handling.",
    createdEntities: ["Job", "WorkPackage"],
    sideEffects: [{ kind: "entity_create", detail: "job.create_linked_shell" }, { kind: "audit", detail: "request.converted_to_job" }],
    communicationTriggers: [],
    auditEvent: "request.converted_to_job",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Requires live server validation." },
    idempotencyScope: { keys: ["tenantId", "requestId", "clientOperationId"], description: "Only one shell job should create from the same request action." },
    policyDependencies: ["D9"]
  },
  {
    commandId: "request.convert_to_quote",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "request.convert_to_quote",
    currentConditions: [{ code: "custom_scope_needed", when: "pricing or scope needs staff composition" }],
    dominantLabel: "Create quote",
    secondaryActions: ["Create job", "Schedule follow-up"],
    requiredFields: ["clientId", "intakeSnapshot"],
    blockingConditions: [{ code: "missing_required_field", when: "intake is incomplete", blockerCopy: "Capture the required request details before composing a quote." }],
    transitionResult: "Creates a draft quote tied to the originating request.",
    createdEntities: ["Quote"],
    sideEffects: [{ kind: "entity_create", detail: "quote.create_draft" }, { kind: "audit", detail: "request.converted_to_quote" }],
    communicationTriggers: [],
    auditEvent: "request.converted_to_quote",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Requires live server validation." },
    idempotencyScope: { keys: ["tenantId", "requestId", "clientOperationId"], description: "Prevent duplicate draft quote creation from repeated submits." },
    policyDependencies: ["D9"]
  },
  {
    commandId: "request.schedule_follow_up",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "request.contact",
    currentConditions: [{ code: "follow_up_needed", when: "request needs more customer info or deferred contact" }],
    dominantLabel: "Schedule follow-up",
    secondaryActions: ["Log contact attempt"],
    requiredFields: ["owner", "dueAt", "reason"],
    blockingConditions: [],
    transitionResult: "Creates FollowUpTask and moves request_status to follow_up_scheduled.",
    createdEntities: ["FollowUpTask"],
    sideEffects: [{ kind: "entity_create", detail: "follow_up_task.create" }, { kind: "audit", detail: "request.follow_up_scheduled" }],
    communicationTriggers: [],
    auditEvent: "request.follow_up_scheduled",
    confirmationTier: "none",
    offlineBehavior: { supported: false, behavior: "Requires live owner resolution." },
    idempotencyScope: { keys: ["tenantId", "requestId", "clientOperationId"], description: "Prevents duplicate follow-up tasks from refresh retries." },
    policyDependencies: []
  },
  {
    commandId: "request.merge_duplicate",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "request.merge",
    currentConditions: [{ code: "duplicate_candidate", when: "exact email or phone match has been confirmed" }],
    dominantLabel: "Merge duplicate",
    secondaryActions: ["Flag for manager review"],
    requiredFields: ["survivingRequestId", "mergedRequestIds"],
    blockingConditions: [{ code: "invalid_state", when: "any downstream record already differs", blockerCopy: "Resolve downstream records before merging these requests." }],
    transitionResult: "Consolidates duplicate requests until downstream entities make the merge irreversible.",
    createdEntities: [],
    sideEffects: [{ kind: "entity_update", detail: "request.merge" }, { kind: "audit", detail: "request.merged" }],
    communicationTriggers: [],
    auditEvent: "request.merged",
    confirmationTier: "high",
    offlineBehavior: { supported: false, behavior: "Needs live conflict checks before merging." },
    idempotencyScope: { keys: ["tenantId", "survivingRequestId", "clientOperationId"], description: "Prevents repeated merge application on refresh." },
    policyDependencies: ["D9"]
  }
];

export const REQUEST_CORE_COMMUNICATIONS: CommunicationTemplate[] = [

];
