import type { CommunicationTemplate, LifecycleCommandContract } from "@nexteam/core";
import { PORTAL_AUTHORIZATION_PROFILE_ID } from "../../../../../../../crm/lifecyclePolicy.js";

export const VISIT_CORE_COMMANDS: LifecycleCommandContract[] = [
  {
    commandId: "job.schedule_visit",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "job.schedule",
    currentConditions: [{ code: "job_open", when: "job is open and at least one work package is authorized" }],
    dominantLabel: "Schedule visit",
    secondaryActions: ["Create follow-up visit"],
    requiredFields: ["visitStart", "visitEnd", "assignedTo"],
    blockingConditions: [{ code: "capacity_conflict", when: "crew or arrival window capacity is exceeded", blockerCopy: "That window is full. Pick a different slot or rebalance the crew." }],
    transitionResult: "Creates or updates a scheduled visit and fires booking confirmation messaging.",
    createdEntities: ["Visit"],
    sideEffects: [{ kind: "communication", detail: "booking_confirmation" }, { kind: "audit", detail: "visit.scheduled" }],
    communicationTriggers: [{ templateId: "booking_confirmation", mode: "manual" }],
    auditEvent: "visit.scheduled",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Scheduling requires live availability checks." },
    idempotencyScope: { keys: ["tenantId", "jobId", "clientOperationId"], description: "Prevents duplicate visit scheduling from a double-submit." },
    policyDependencies: ["D9", "D12"]
  },
  {
    commandId: "visit.start_travel",
    type: "command",
    actorSurface: "field_mobile",
    requiredPermission: "visit.start",
    currentConditions: [{ code: "visit_scheduled", when: "crew is leaving for a scheduled visit" }],
    dominantLabel: "Start travel",
    secondaryActions: ["Call customer", "Directions"],
    requiredFields: [],
    blockingConditions: [{ code: "offline_restricted", when: "visit not present on the local device", blockerCopy: "Sync the latest visit details to this device before starting travel." }],
    transitionResult: "Moves visit travel status into traveling.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "visit.travel_started" }],
    communicationTriggers: [],
    auditEvent: "visit.travel_started",
    confirmationTier: "none",
    offlineBehavior: { supported: true, behavior: "Can be recorded locally and synced later for the technician's assigned work." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "Duplicate start-travel taps collapse into one transition." },
    policyDependencies: ["D16"]
  },
  {
    commandId: "visit.mark_arrived",
    type: "command",
    actorSurface: "field_mobile",
    requiredPermission: "visit.start",
    currentConditions: [{ code: "traveling", when: "crew has arrived on site" }],
    dominantLabel: "Mark arrived",
    secondaryActions: ["Call customer"],
    requiredFields: [],
    blockingConditions: [],
    transitionResult: "Moves visit travel status into arrived and visit status into in_progress.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "visit.arrived" }],
    communicationTriggers: [],
    auditEvent: "visit.arrived",
    confirmationTier: "none",
    offlineBehavior: { supported: true, behavior: "Can be recorded locally and synced later for the technician's assigned work." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "Duplicate arrival taps collapse into one transition." },
    policyDependencies: ["D16"]
  },
  {
    commandId: "visit.complete",
    type: "command",
    actorSurface: "field_mobile",
    requiredPermission: "visit.complete",
    currentConditions: [{ code: "visit_in_progress", when: "visit has started and required field documentation is complete" }],
    dominantLabel: "Complete visit",
    secondaryActions: ["Pause visit", "Add media"],
    requiredFields: ["fieldDocumentationStatus"],
    blockingConditions: [{ code: "missing_required_field", when: "field documentation incomplete", blockerCopy: "Finish the required field documentation before completing this visit." }],
    transitionResult: "Marks the visit completed locally first when needed and syncs admin closeout attention later.",
    createdEntities: [],
    sideEffects: [{ kind: "notification", detail: "create_admin_closeout_attention" }, { kind: "audit", detail: "visit.completed" }],
    communicationTriggers: [],
    auditEvent: "visit.completed",
    confirmationTier: "standard",
    offlineBehavior: { supported: true, behavior: "Technician can complete locally and sync on reconnect, with conflict checks on sync." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "Duplicate local complete actions collapse to one final completion event." },
    policyDependencies: ["D11", "D16"]
  },
  {
    commandId: "visit.unable_to_complete",
    type: "command",
    actorSurface: "field_mobile",
    requiredPermission: "visit.complete",
    currentConditions: [{ code: "visit_started_or_arrived", when: "crew needs to log an explicit unable-to-complete outcome" }],
    dominantLabel: "Log unable to complete",
    secondaryActions: ["Reschedule visit", "Call customer"],
    requiredFields: ["outcomeReason"],
    blockingConditions: [],
    transitionResult: "Moves visit_status to unable_to_complete and records the named outcome policy for later billing review.",
    createdEntities: ["OutcomeEvent"],
    sideEffects: [{ kind: "notification", detail: "create_admin_attention_from_outcome" }, { kind: "audit", detail: "visit.unable_to_complete" }],
    communicationTriggers: [],
    auditEvent: "visit.unable_to_complete",
    confirmationTier: "standard",
    offlineBehavior: { supported: true, behavior: "Can save locally and sync outcome details later." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "One outcome event per explicit submit." },
    policyDependencies: ["D13", "D16"]
  },
  {
    commandId: "visit.reschedule",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "visit.reschedule",
    currentConditions: [{ code: "visit_not_started", when: "visit is scheduled but not started" }],
    dominantLabel: "Reschedule visit",
    secondaryActions: ["Cancel visit", "Counter-propose"],
    requiredFields: ["visitStart", "visitEnd", "reason"],
    blockingConditions: [
      { code: "availability_conflict", when: "technician is unavailable", blockerCopy: "That technician is not available in this window." },
      { code: "capacity_conflict", when: "arrival window capacity is full", blockerCopy: "That arrival window is full. Pick a new one." }
    ],
    transitionResult: "Revises the visit schedule, preserves history, and sends a reschedule notice every time.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "visit_rescheduled" }, { kind: "audit", detail: "visit.rescheduled" }],
    communicationTriggers: [{ templateId: "visit_rescheduled", mode: "auto" }],
    auditEvent: "visit.rescheduled",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Reschedule is online only because it needs availability and capacity checks." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "Retry-safe by visit and revision request." },
    policyDependencies: ["D7", "D12"]
  },
  {
    commandId: "visit.cancel",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "visit.cancel",
    currentConditions: [{ code: "visit_exists", when: "a scheduled visit needs cancelation" }],
    dominantLabel: "Cancel visit",
    secondaryActions: ["Reschedule visit"],
    requiredFields: ["cancellationSource", "reason"],
    blockingConditions: [],
    transitionResult: "Cancels the visit, creates job attention follow-up, and keeps the next dominant action explicit rather than auto-selected.",
    createdEntities: ["FollowUpTask"],
    sideEffects: [{ kind: "communication", detail: "visit_canceled" }, { kind: "audit", detail: "visit.canceled" }],
    communicationTriggers: [{ templateId: "visit_canceled", mode: "auto" }],
    auditEvent: "visit.canceled",
    confirmationTier: "high",
    offlineBehavior: { supported: false, behavior: "Cancelation is online only." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "Prevents duplicate cancelation writes." },
    policyDependencies: ["D7", "D12"]
  },
  {
    commandId: "job.create_followup_visit",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "job.schedule",
    currentConditions: [{ code: "follow_up_needed", when: "more field work is needed on the same job" }],
    dominantLabel: "Create follow-up visit",
    secondaryActions: ["Reopen for follow-up"],
    requiredFields: ["workPackageId", "label"],
    blockingConditions: [],
    transitionResult: "Creates follow-up work on the same job rather than creating a new job.",
    createdEntities: ["Visit", "WorkPackage"],
    sideEffects: [{ kind: "entity_create", detail: "job.followup_visit_created" }, { kind: "audit", detail: "job.followup_visit_created" }],
    communicationTriggers: [],
    auditEvent: "job.followup_visit_created",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Follow-up scheduling is online only." },
    idempotencyScope: { keys: ["tenantId", "jobId", "clientOperationId"], description: "One follow-up creation per staff action." },
    policyDependencies: ["D18"]
  }
];

export const VISIT_CORE_COMMUNICATIONS: CommunicationTemplate[] = [
  {
    templateId: "booking_confirmation",
    trigger: "job.schedule_visit",
    channels: ["email", "sms"],
    mode: "manual",
    recipientResolution: "Use the job contact delivery preferences for the scheduled visit.",
    previewRequired: true,
    suppressionRule: "Suppress a channel if that channel is disabled for reminders.",
    idempotencyScope: "visit.booking_confirmation:{visitId}:{revisionCount}",
    failureBehavior: "Keep the visit scheduled and create a delivery failure attention item.",
    auditEvent: "visit.booking_confirmation_sent",
    attachmentPolicy: "No attachments."
  },
  {
    templateId: "visit_rescheduled",
    trigger: "visit.reschedule",
    channels: ["email", "sms"],
    mode: "auto",
    recipientResolution: "Send to the visit's current client contact on every successful reschedule.",
    previewRequired: true,
    suppressionRule: "Skip a specific channel only if the client disabled that reminder channel first.",
    idempotencyScope: "visit.rescheduled:{visitId}:{revisionCount}",
    failureBehavior: "Record failure and keep the reschedule intact.",
    auditEvent: "visit.rescheduled_notified",
    attachmentPolicy: "No attachments."
  },
  {
    templateId: "visit_canceled",
    trigger: "visit.cancel",
    channels: ["email", "sms"],
    mode: "auto",
    recipientResolution: "Use the active visit contact record.",
    previewRequired: false,
    suppressionRule: "Suppress only when customer communications are disabled before cancelation is executed.",
    idempotencyScope: "visit.canceled:{visitId}:{cancellationId}",
    failureBehavior: "Keep the cancelation and create an internal delivery-failure task.",
    auditEvent: "visit.canceled_notified",
    attachmentPolicy: "No attachments."
  }
];
