import type { Request, Response } from "express";
import type { CrmRouteContext } from "../../runtime/routeRuntime.js";
import { agreementCreateInputSchema, agreementPatchInputSchema } from "./agreementFoundation.js";

export function registerAgreementRoutes(context: CrmRouteContext): void {
  const { app, agreementService, defaultTenantId, env, requireQuoteAccess, sendRouteError } = context;
  const tenantFrom = (req: Request) => typeof req.query.tenantId === "string" && req.query.tenantId.trim() ? req.query.tenantId : (typeof req.body?.tenantId === "string" && req.body.tenantId.trim() ? req.body.tenantId : defaultTenantId(env));
  app.get("/api/crm/agreements", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireQuoteAccess(req, tenantId, "listAgreements"); res.json({ ok: true, tenantId, actorRole: access.role, agreements: await agreementService().list(tenantId) }); } catch (error) { sendRouteError(res, error); } });
  app.get("/api/crm/agreements/:id", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireQuoteAccess(req, tenantId, "getAgreement"); const agreement = await agreementService().get(tenantId, req.params.id ?? ""); if (!agreement) return res.status(404).json({ ok: false, error: "Agreement was not found." }); res.json({ ok: true, tenantId, actorRole: access.role, agreement, events: await agreementService().events(tenantId, agreement.id) }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/agreements", async (req: Request, res: Response) => { try { const input = agreementCreateInputSchema.parse(req.body); const access = await requireQuoteAccess(req, input.tenantId, "createAgreement"); const agreement = await agreementService().create(input, access.tenantUserId); res.status(201).json({ ok: true, tenantId: input.tenantId, actorRole: access.role, agreement }); } catch (error) { sendRouteError(res, error); } });
  app.patch("/api/crm/agreements/:id", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireQuoteAccess(req, tenantId, "updateAgreement"); const agreement = await agreementService().update(tenantId, req.params.id ?? "", agreementPatchInputSchema.parse(req.body), access.tenantUserId); res.json({ ok: true, tenantId, actorRole: access.role, agreement }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/agreements/:id/:command", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const command = req.params.command; if (command !== "activated" && command !== "paused" && command !== "resumed" && command !== "cancelled") return res.status(400).json({ ok: false, error: "Unsupported agreement command." }); const access = await requireQuoteAccess(req, tenantId, `${command}Agreement`); const agreement = await agreementService().transition(tenantId, req.params.id ?? "", command, access.tenantUserId); res.json({ ok: true, tenantId, actorRole: access.role, agreement }); } catch (error) { sendRouteError(res, error); } });
}
