import type { CommunicationTemplate, LifecycleCommandContract } from "@nexteam/core";
import { PORTAL_AUTHORIZATION_PROFILE_ID } from "../../../../../../../crm/lifecyclePolicy.js";

export const PAYMENT_RAILS_COMMANDS: LifecycleCommandContract[] = [
  {
    commandId: "quote.collect_deposit",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "deposit.collect",
    currentConditions: [{ code: "deposit_required", when: "quote approval path requires a deposit that is still unpaid" }],
    dominantLabel: "Collect deposit",
    secondaryActions: ["Waive deposit"],
    requiredFields: ["amount", "paymentMethod"],
    blockingConditions: [],
    transitionResult: "Collects the required deposit as a standalone office action and applies it to the quote authorization rail.",
    createdEntities: ["Payment", "Allocation"],
    sideEffects: [{ kind: "payment_attempt", detail: "deposit.collect" }, { kind: "audit", detail: "deposit.collected" }],
    communicationTriggers: [{ templateId: "payment_receipt", mode: "review_gated" }],
    auditEvent: "deposit.collected",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Deposit collection requires connection." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "One office-side deposit collection per submit." },
    policyDependencies: ["D2", "D3", "D4", "D5"]
  },
  {
    commandId: "quote.waive_deposit",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "deposit.waive",
    currentConditions: [{ code: "deposit_required", when: "deposit is configured but an authorized waiver is being granted" }],
    dominantLabel: "Waive deposit",
    secondaryActions: ["Collect deposit"],
    requiredFields: ["waiverReason"],
    blockingConditions: [],
    transitionResult: "Removes the deposit blocker from authorization while preserving an audited waiver trail.",
    createdEntities: [],
    sideEffects: [{ kind: "audit", detail: "deposit.waived" }],
    communicationTriggers: [],
    auditEvent: "deposit.waived",
    confirmationTier: "high",
    offlineBehavior: { supported: false, behavior: "Waivers are online only." },
    idempotencyScope: { keys: ["tenantId", "quoteId", "clientOperationId"], description: "One waiver decision per submit." },
    policyDependencies: ["D2", "D3"]
  },
  {
    commandId: "portal.invoice_pay",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "invoice_open", when: "portal customer is paying an open invoice" }],
    dominantLabel: "Pay invoice",
    secondaryActions: ["View invoice"],
    requiredFields: ["paymentMethod", "amount"],
    blockingConditions: [
      { code: "amount_exceeds_balance", when: "payment amount is above the live balance", blockerCopy: "That amount is higher than the remaining balance." },
      { code: "amount_below_minimum", when: "partial payment is attempted without an active payment schedule", blockerCopy: "This invoice requires the full remaining balance right now." },
      { code: "payment_method_invalid", when: "selected payment method failed validation", blockerCopy: "Use a valid payment method to continue." }
    ],
    transitionResult: "Collects payment against the open invoice and refreshes the live balance before charging.",
    createdEntities: ["Payment", "Allocation", "ReceiptReview"],
    sideEffects: [{ kind: "payment_attempt", detail: "portal.invoice_pay" }, { kind: "audit", detail: "payment.collected" }],
    communicationTriggers: [{ templateId: "payment_receipt", mode: "review_gated" }],
    auditEvent: "payment.collected",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Portal payment is online only." },
    idempotencyScope: { keys: ["tenantId", "invoiceId", "clientOperationId"], description: "One payment attempt per client operation id." },
    policyDependencies: ["D19"]
  },
  {
    commandId: "payment.collect",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "payment.collect",
    currentConditions: [{ code: "invoice_open", when: "staff is collecting an invoice payment" }],
    dominantLabel: "Collect payment",
    secondaryActions: ["Retry payment", "View invoice"],
    requiredFields: ["amount", "method"],
    blockingConditions: [{ code: "amount_below_minimum", when: "partial payment is not allowed for this invoice", blockerCopy: "This invoice needs the full balance because no payment schedule is active." }],
    transitionResult: "Creates the payment and allocation records, then pauses at receipt review before anything customer-facing sends.",
    createdEntities: ["Payment", "Allocation", "ReceiptReview"],
    sideEffects: [{ kind: "payment_attempt", detail: "payment.collect" }, { kind: "audit", detail: "payment.collected" }],
    communicationTriggers: [{ templateId: "payment_receipt", mode: "review_gated" }],
    auditEvent: "payment.collected",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Money movement requires connection." },
    idempotencyScope: { keys: ["tenantId", "invoiceId", "clientOperationId"], description: "One payment collect action per operator submit." },
    policyDependencies: ["D19"]
  },
  {
    commandId: "payment.refund",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "payment.refund",
    currentConditions: [{ code: "payment_succeeded", when: "a succeeded payment exists that can be refunded" }],
    dominantLabel: "Refund payment",
    secondaryActions: ["View ledger"],
    requiredFields: ["amount", "reason"],
    blockingConditions: [],
    transitionResult: "Creates a refund transaction rather than a new allocation type and adjusts downstream balances.",
    createdEntities: ["Payment"],
    sideEffects: [{ kind: "payment_attempt", detail: "payment.refund" }, { kind: "audit", detail: "payment.refunded" }],
    communicationTriggers: [],
    auditEvent: "payment.refunded",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Refunds require live processor state." },
    idempotencyScope: { keys: ["tenantId", "paymentId", "clientOperationId"], description: "One refund attempt per submit." },
    policyDependencies: ["D6"]
  },
  {
    commandId: "payment.retry",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "payment.retry",
    currentConditions: [{ code: "payment_failed", when: "a failed attempt exists and recovery is allowed" }],
    dominantLabel: "Retry payment",
    secondaryActions: ["Collect payment", "Send pay link"],
    requiredFields: ["method"],
    blockingConditions: [],
    transitionResult: "Creates a new payment attempt against the same invoice or quote bridge context.",
    createdEntities: ["Payment"],
    sideEffects: [{ kind: "payment_attempt", detail: "payment.retry" }, { kind: "audit", detail: "payment.retried" }],
    communicationTriggers: [],
    auditEvent: "payment.retried",
    confirmationTier: "financial",
    offlineBehavior: { supported: false, behavior: "Retry requires live processor access." },
    idempotencyScope: { keys: ["tenantId", "paymentId", "clientOperationId"], description: "One retry attempt per submit." },
    policyDependencies: ["D19"]
  }
];

export const PAYMENT_RAILS_COMMUNICATIONS: CommunicationTemplate[] = [
  {
    templateId: "payment_reminder",
    trigger: "overdue_scheduler",
    channels: ["email", "sms"],
    mode: "auto",
    recipientResolution: "Resolve against the invoice's billing contact.",
    previewRequired: false,
    suppressionRule: "Suppress only when the invoice is no longer open or already paid.",
    idempotencyScope: "invoice.payment_reminder:{invoiceId}:{dueBucket}:{scheduledAt}",
    failureBehavior: "Log failure and retry on the next scheduler pass.",
    auditEvent: "invoice.payment_reminder_sent",
    attachmentPolicy: "Attach the invoice only."
  },
  {
    templateId: "payment_receipt",
    trigger: "payment.collect",
    channels: ["email"],
    mode: "review_gated",
    recipientResolution: "Use the paying customer's email after receipt review is approved.",
    previewRequired: true,
    suppressionRule: "Never auto-send. Receipt review approval is mandatory every time.",
    idempotencyScope: "payment.receipt:{paymentId}:{receiptReviewId}",
    failureBehavior: "Keep the payment settled and leave the receipt review pending until staff resolves it.",
    auditEvent: "payment.receipt_sent",
    attachmentPolicy: "Attach the approved receipt and any selected closeout files."
  }
];
