import React, { useState } from "react";
import { PlatformMark } from "../branding/ProductBranding";
import { NexTeamApplicationShell } from "./NexTeamApplicationShell";
import { NexTeamProductHeader } from "./NexTeamProductHeader";
import { NexCommandHeader } from "./NexCommandHeader";
import { NexSuiteHeader } from "./NexSuiteHeader";

type HeaderVariant = "tenant" | "admin";
function reviewVariant(): HeaderVariant { return typeof window !== "undefined" && new URLSearchParams(window.location.search).get("variant") === "admin" ? "admin" : "tenant"; }
function TenantHeaderReview(): React.ReactElement { const [menuOpen, setMenuOpen] = useState(false); const [notice, setNotice] = useState("Representative design controls only — no workspace action will run."); return <section className="header-review-variant" aria-label="NexSuite Header preview"><NexSuiteHeader product="nexops" menuOpen={menuOpen} onToggleMenu={() => setMenuOpen((open) => !open)} onSignOut={() => setNotice("Sign Out treatment selected.")} /><div className="header-review-body"><p className="ui-eyebrow">NexSuite Header</p><h2>{menuOpen ? "Menu state: open" : "NexOps consumer"}</h2><p>{notice}</p></div></section>; }
function AdminHeaderReview(): React.ReactElement { const [menuOpen, setMenuOpen] = useState(false); const [notice, setNotice] = useState("Representative design controls only — no operator action will run."); return <section className="header-review-variant header-review-admin" aria-label="NexCommand Header preview"><NexCommandHeader menuOpen={menuOpen} onToggleMenu={() => setMenuOpen((open) => !open)} onSignOut={() => setNotice("Sign Out treatment selected.")} /><div className="header-review-body"><p className="ui-eyebrow">NexCommand Header</p><h2>{menuOpen ? "Menu state: open" : "Internal consumer"}</h2><p>{notice}</p></div></section>; }
export function HeaderReviewPage(): React.ReactElement { const [variant, setVariant] = useState<HeaderVariant>(reviewVariant); const setReviewVariant = (next: HeaderVariant) => { window.history.replaceState({}, "", `/design-system/layout-parts/header?variant=${next}`); setVariant(next); }; return <NexTeamApplicationShell className="header-review-shell" navigationLabel="NexSuite design navigation" mobileNavigationMode="collapse" header={<NexTeamProductHeader className="header-review-shell__topbar" ariaLabel="NexSuite design Header" brand={<div className="header-review-shell__brand"><PlatformMark decorative /><span>NexSuite Design</span></div>} context={<span>Design system</span>} />} navigation={<nav className="header-review-shell__navigation"><a className="is-active" href="/nexcommand?area=templates&template=global">Templates</a></nav>}><section className="header-review-page"><header className="header-review-page__intro"><div><p className="ui-eyebrow">NexSuite design system · layout part</p><h1>NexCommandHeader.tsx / NexSuiteHeader.tsx</h1><p>Live review surface rendering the two current Header Layout Parts directly with representative review controls.</p></div><div className="header-review-page__tabs" aria-label="Header variant"><button type="button" className={variant === "tenant" ? "active" : ""} onClick={() => setReviewVariant("tenant")}>NexSuite</button><button type="button" className={variant === "admin" ? "active" : ""} onClick={() => setReviewVariant("admin")}>NexCommand</button></div></header>{variant === "tenant" ? <TenantHeaderReview /> : <AdminHeaderReview />}<p className="header-review-page__hint">Resize below 880px to inspect the current mobile Header behavior.</p></section></NexTeamApplicationShell>; }
