import React, { useState } from "react";
import type { TenantBranding } from "@nexteam/core";
import { PlatformMark } from "../branding/ProductBranding";
import { NexOpsSharedMobileBar, NexOpsSharedWebTopbar } from "../../features/nexopsShell/components/NexOpsHeader";
import { NexTeamProductHeader } from "./NexTeamProductHeader";

const REVIEW_TENANT: TenantBranding = { tenantId: "harbor-hearth-demo", displayName: "Harbor & Hearth Services", colors: {}, source: "default", updatedBy: "design-system", updatedAt: "2026-08-20T00:00:00.000Z" };
type HeaderVariant = "tenant" | "admin";
function reviewVariant(): HeaderVariant { return typeof window !== "undefined" && new URLSearchParams(window.location.search).get("variant") === "admin" ? "admin" : "tenant"; }
function ReviewIconButton(props: { label: string; glyph: string; onClick: () => void; badge?: boolean }): React.ReactElement { return <button className="nexops-web-icon-button header-review-icon-button" type="button" aria-label={props.label} onClick={props.onClick}><span aria-hidden="true">{props.glyph}</span>{props.badge ? <span className="header-review-notification-badge">3</span> : null}</button>; }
function TenantHeaderReview(): React.ReactElement { const [modulesOpen, setModulesOpen] = useState(false); const [notice, setNotice] = useState("Representative design data only — no workspace action will run."); const controls = <><ReviewIconButton label="Preview capture control" glyph="◉" onClick={() => setNotice("Capture utility selected.")} /><ReviewIconButton label="Preview notifications" glyph="♧" badge onClick={() => setNotice("Notifications utility selected.")} /><ReviewIconButton label="Preview settings" glyph="⚙" onClick={() => setNotice("Settings utility selected.")} /><span>alex@harborhearth.example</span><button type="button" onClick={() => setNotice("Sign-out treatment selected.")}>Sign out</button></>; return <section className="header-review-variant" aria-label="Tenant operational Header preview"><NexOpsSharedWebTopbar tenantBranding={REVIEW_TENANT} tenantId={REVIEW_TENANT.tenantId} product="nexops" moduleTitle="Operations" moduleSwitcherOpen={modulesOpen} onToggleModuleSwitcher={() => setModulesOpen((open) => !open)} accountTools={controls} searchPlaceholder="Search operations..." /><NexOpsSharedMobileBar tenantBranding={REVIEW_TENANT} tenantId={REVIEW_TENANT.tenantId} product="nexops" onBrandClick={() => setNotice("Home identity selected.")} rightControls={<><ReviewIconButton label="Preview capture control" glyph="◉" onClick={() => setNotice("Capture utility selected.")} /><ReviewIconButton label="Preview notifications" glyph="♧" badge onClick={() => setNotice("Notifications utility selected.")} /><button className="nexops-mobile-menu-button" type="button" onClick={() => setNotice("Mobile navigation treatment selected.")}>☰</button></>} /><div className="header-review-body"><p className="ui-eyebrow">Tenant / operational</p><h2>NexOps reference composition</h2><p>{modulesOpen ? "Modules control is open in this review state." : notice}</p></div></section>; }
function AdminHeaderReview(): React.ReactElement { const [notice, setNotice] = useState("Representative design data only — no admin action will run."); return <section className="header-review-variant header-review-admin" aria-label="Internal admin Header preview"><NexTeamProductHeader className="nexcommand__topbar" ariaLabel="NexCommand header" navigation={<button className="nexcommand__menu" type="button" aria-label="Open NexCommand navigation" onClick={() => setNotice("Admin navigation treatment selected.")}>☰</button>} brand={<div className="nexcommand__brand"><PlatformMark decorative /><span>NexCommand</span></div>} context={<div className="nexcommand__environment"><span>STAGING</span><small>nexstage.nexteam.studio</small></div>} utilities={<button className="nexcommand__signout" type="button" onClick={() => setNotice("Sign-out treatment selected.")}>Sign out</button>} /><div className="header-review-body"><p className="ui-eyebrow">Internal / admin</p><h2>NexCommand reference composition</h2><p>{notice}</p></div></section>; }
export function HeaderReviewPage(): React.ReactElement { const [variant, setVariant] = useState<HeaderVariant>(reviewVariant); const setReviewVariant = (next: HeaderVariant) => { window.history.replaceState({}, "", `/design-system/layout-parts/header?variant=${next}`); setVariant(next); }; return <main className="header-review-page"><header className="header-review-page__intro"><div><p className="ui-eyebrow">NexSuite design system · layout part</p><h1>Header</h1><p>Live review surface using the reusable Header implementation and deterministic representative data.</p></div><div className="header-review-page__tabs" aria-label="Header variant"><button type="button" className={variant === "tenant" ? "active" : ""} onClick={() => setReviewVariant("tenant")}>Tenant / Operational</button><button type="button" className={variant === "admin" ? "active" : ""} onClick={() => setReviewVariant("admin")}>Internal / Admin</button></div></header>{variant === "tenant" ? <TenantHeaderReview /> : <AdminHeaderReview />}<p className="header-review-page__hint">Resize the browser below 880px to inspect the current mobile Header behavior.</p></main>; }
