import React from "react";
import { NexSuiteSidebar, type NexSuiteSidebarItem } from "./NexSuiteSidebar";
import { PlatformMark } from "../branding/ProductBranding";
import { NexTeamApplicationShell } from "./NexTeamApplicationShell";
import { NexTeamProductHeader } from "./NexTeamProductHeader";

export function SidebarReviewPage(): React.ReactElement {
  const [selected, setSelected] = React.useState("home");
  const [open, setOpen] = React.useState(true);
  const items: NexSuiteSidebarItem[] = [
    { id: "home", label: "Home", icon: "⌂", active: selected === "home", onSelect: () => setSelected("home") },
    { id: "clients", label: "Clients", icon: "◫", active: selected === "clients", onSelect: () => setSelected("clients") },
    { id: "quotes", label: "Quotes", icon: "▤", active: selected === "quotes", onSelect: () => setSelected("quotes") },
    { id: "jobs", label: "Jobs", icon: "⌁", active: selected === "jobs", onSelect: () => setSelected("jobs") },
    { id: "settings", label: "Settings", icon: "⚙", active: selected === "settings", onSelect: () => setSelected("settings") }
  ];
  return <NexTeamApplicationShell className="header-review-shell" navigationLabel="NexSuite design navigation" mobileNavigationMode="collapse" header={<NexTeamProductHeader className="header-review-shell__topbar" ariaLabel="NexSuite design Header" brand={<div className="header-review-shell__brand"><PlatformMark decorative /><span>NexSuite Design</span></div>} context={<span>Design system</span>} />} navigation={<nav className="header-review-shell__navigation"><a className="is-active" href="/nexcommand?area=templates">Templates</a></nav>}><section className="sidebar-review-page"><header className="sidebar-review-page__intro"><p className="ui-eyebrow">NexSuite design system · layout part</p><h1>Sidebar</h1><p>Current NexCommand navigation is shown below as a live reference specimen. It is not a final Global Sidebar design.</p></header><section className="sidebar-review-specimen" aria-label="Sidebar specimen under review"><header><p className="ui-eyebrow">Component specimen</p><h2>NexCommand Sidebar — current reference</h2><p>The surrounding NexSuite shell is review navigation. This framed Sidebar is the component under review.</p></header><div className="sidebar-review-specimen__frame"><NexCommandSidebar area="templates" liveState="IDLE" onSelect={openNexCommandArea} /></div></section></section></NexTeamApplicationShell>;
  return <NexTeamApplicationShell className="header-review-shell" navigationLabel="NexSuite design navigation" mobileNavigationMode="collapse" header={<NexTeamProductHeader className="header-review-shell__topbar" ariaLabel="NexSuite design Header" brand={<div className="header-review-shell__brand"><PlatformMark decorative /><span>NexSuite Design</span></div>} context={<span>Design system</span>} />} navigation={<nav className="header-review-shell__navigation"><a className="is-active" href="/nexcommand?area=templates&template=global">Templates</a></nav>}><section className="sidebar-review-page"><header className="sidebar-review-page__intro"><p className="ui-eyebrow">NexSuite design system · Layout Part</p><h1>NexSuiteSidebar.tsx</h1><p>Live review surface rendering the current reusable Sidebar Layout Part directly. Select an item or use the close control on mobile.</p></header><section className="sidebar-review-specimen" aria-label="NexSuite Sidebar Layout Part"><header><p className="ui-eyebrow">Live Layout Part</p><h2>NexSuiteSidebar</h2><p>Representative navigation data is supplied by this review Page; layout, drawer behavior, and selected state come from the current shared file.</p></header><div className="sidebar-review-specimen__frame"><NexSuiteSidebar items={items} open={open} onClose={() => setOpen(false)} onSelect={() => setOpen(true)} /></div></section></section></NexTeamApplicationShell>;
}
