import type { Request, Response } from "express";
import type { CrmRouteContext } from "../../runtime/routeRuntime.js";
import { createJobCostFactInputSchema, voidJobCostFactInputSchema } from "./jobCostingFoundation.js";

export function registerJobCostingRoutes(context: CrmRouteContext): void {
  const { app, defaultTenantId, env, jobCostingService, providerForTenant, requireBillingAccess, sendRouteError } = context;
  const tenantFrom = (req: Request) => typeof req.query.tenantId === "string" && req.query.tenantId.trim() ? req.query.tenantId : (typeof req.body?.tenantId === "string" && req.body.tenantId.trim() ? req.body.tenantId : defaultTenantId(env));
  const requireJob = async (tenantId: string, jobId: string) => { const job = await providerForTenant(tenantId).getJobDetail({ id: jobId }); return job; };
  app.get("/api/crm/jobs/:jobId/cost-facts", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "listJobCostFacts"); const jobId = req.params.jobId ?? ""; await requireJob(tenantId, jobId); res.json({ ok: true, tenantId, actorRole: access.role, costFacts: await jobCostingService().listFacts(tenantId, jobId), events: await jobCostingService().events(tenantId, jobId) }); } catch (error) { sendRouteError(res, error); } });
  app.get("/api/crm/jobs/:jobId/profitability", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "getJobProfitability"); const jobId = req.params.jobId ?? ""; await requireJob(tenantId, jobId); const invoices = await providerForTenant(tenantId).getInvoices(); res.json({ ok: true, tenantId, actorRole: access.role, profitability: await jobCostingService().summarize(tenantId, jobId, invoices) }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/jobs/:jobId/cost-facts", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "createJobCostFact"); const jobId = req.params.jobId ?? ""; await requireJob(tenantId, jobId); const input = createJobCostFactInputSchema.parse({ ...req.body, tenantId, jobId }); const costFact = await jobCostingService().create(input, access.tenantUserId); res.status(201).json({ ok: true, tenantId, actorRole: access.role, costFact }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/jobs/:jobId/cost-facts/:id/void", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "voidJobCostFact"); const jobId = req.params.jobId ?? ""; await requireJob(tenantId, jobId); const costFact = await jobCostingService().void(tenantId, req.params.id ?? "", voidJobCostFactInputSchema.parse(req.body), access.tenantUserId); if (costFact.jobId !== jobId) return res.status(404).json({ ok: false, error: "Cost fact was not found." }); res.json({ ok: true, tenantId, actorRole: access.role, costFact }); } catch (error) { sendRouteError(res, error); } });
}
