import React, { useEffect, useState } from "react";
import type { User } from "firebase/auth";

type TenantProfileResponse = { tenant: { id: string; name: string; timezone: string; lifecycleState?: "ACTIVE" | "DISABLED_ARCHIVED"; branding: { assistantName: string } }; profile: Record<string, unknown> | null; branding: { logo?: { url?: string } } | null; subscription: { plan: string; status: string } | null; access: Array<{ displayName: string; email: string | null; role: string; active: boolean; firebaseUidBound: boolean }> };
async function request(user: User, path: string, init?: RequestInit): Promise<TenantProfileResponse> { const token = await user.getIdToken(); const response = await fetch(path, { ...init, headers: { authorization: `Bearer ${token}`, "content-type": "application/json" } }); const body = await response.json() as TenantProfileResponse & { error?: string }; if (!response.ok) throw new Error(body.error ?? "Tenant profile is unavailable."); return body; }

export function NexCommandTenantProfilePanel({ user, tenantId, onBack }: { user: User | null; tenantId: string; onBack: () => void }): React.ReactElement {
  const [data, setData] = useState<TenantProfileResponse | null>(null); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = async (): Promise<void> => { if (!user) return; setData(await request(user, `/api/platform/admin/tenants/${encodeURIComponent(tenantId)}/profile`)); };
  useEffect(() => { void load().catch(() => setMessage("Tenant profile could not be loaded.")); }, [tenantId, user]);
  if (!data) return <section className="nexcommand__panel"><button type="button" onClick={onBack}>Back to tenants</button><p>{message || "Loading tenant profile…"}</p></section>;
  const profile = data.profile ?? {}; const value = (key: string): string => String(profile[key] ?? "");
  async function save(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!user) return; const form = new FormData(event.currentTarget); setSaving(true); setMessage(""); try { const areas = String(form.get("serviceAreas") ?? "").split(",").map((entry) => entry.trim()).filter(Boolean); await request(user, `/api/platform/admin/tenants/${encodeURIComponent(tenantId)}/profile`, { method: "PATCH", body: JSON.stringify({ legalName: form.get("legalName") || undefined, dbaName: form.get("dbaName") || undefined, website: form.get("website") || undefined, primaryContact: form.get("primaryName") ? { name: form.get("primaryName"), title: form.get("primaryTitle") || undefined, email: form.get("primaryEmail") || undefined, phone: form.get("primaryPhone") || undefined } : undefined, billingContact: form.get("billingName") ? { name: form.get("billingName"), title: form.get("billingTitle") || undefined, email: form.get("billingEmail") || undefined, phone: form.get("billingPhone") || undefined } : undefined, serviceAddress: addressFrom(form, "service"), billingAddress: addressFrom(form, "billing"), serviceAreas: areas, taxCountry: form.get("taxCountry") || undefined, taxIdLast4: form.get("taxIdLast4") || undefined, locale: form.get("locale") || "en-US", tenant: { name: form.get("name"), timezone: form.get("timezone"), lifecycleState: form.get("lifecycleState"), assistantName: form.get("assistantName"), logoUrl: form.get("logoUrl") || undefined } }) }); await load(); setEditing(false); setMessage("Tenant profile saved."); } catch { setMessage("The tenant profile was not saved. Check the highlighted field formats."); } finally { setSaving(false); } }
  return <section className="nexcommand__panel tenant-profile"><button type="button" onClick={onBack}>Back to tenants</button><div className="tenant-profile__heading"><div>{data.branding?.logo?.url ? <img src={data.branding.logo.url} alt="" /> : <span>{data.tenant.name.slice(0, 1)}</span>}<div><p className="ui-eyebrow">Tenant profile</p><h2>{data.tenant.name}</h2><p>{data.subscription?.plan ?? "No plan"} · {data.subscription?.status ?? "No subscription"}</p></div></div><button type="button" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit tenant"}</button></div>
    <form onSubmit={(event) => void save(event)}><fieldset disabled={!editing || saving}><div className="tenant-profile__grid"><label>Tenant name<input name="name" defaultValue={data.tenant.name} required /></label><label>Legal business name<input name="legalName" defaultValue={value("legalName")} /></label><label>DBA / public name<input name="dbaName" defaultValue={value("dbaName")} /></label><label>Website<input name="website" type="url" defaultValue={value("website")} /></label><label>Timezone<input name="timezone" defaultValue={data.tenant.timezone} required /></label><label>Locale<input name="locale" defaultValue={value("locale") || "en-US"} required /></label><label>Assistant name<input name="assistantName" defaultValue={data.tenant.branding.assistantName} required /></label><label>Logo URL<input name="logoUrl" type="url" defaultValue={data.branding?.logo?.url ?? ""} /></label><label>Service areas (comma separated)<input name="serviceAreas" defaultValue={Array.isArray(profile.serviceAreas) ? profile.serviceAreas.join(", ") : ""} /></label><label>Tax country (2 letters)<input name="taxCountry" maxLength={2} defaultValue={value("taxCountry")} /></label><label>Tax ID last four only<input name="taxIdLast4" maxLength={4} defaultValue={value("taxIdLast4")} /></label><label>Status<select name="lifecycleState" defaultValue={data.tenant.lifecycleState ?? "ACTIVE"}><option value="ACTIVE">Active</option><option value="DISABLED_ARCHIVED">Archived</option></select></label></div><h3>Primary contact</h3><ContactFields prefix="primary" contact={profile.primaryContact as Record<string, unknown> | undefined} /><h3>Billing contact</h3><ContactFields prefix="billing" contact={profile.billingContact as Record<string, unknown> | undefined} /><h3>Service address</h3><AddressFields prefix="service" address={profile.serviceAddress as Record<string, unknown> | undefined} /><h3>Billing address</h3><AddressFields prefix="billing" address={profile.billingAddress as Record<string, unknown> | undefined} /></fieldset>{editing ? <button type="submit" disabled={saving}>{saving ? "Saving…" : "Save tenant changes"}</button> : null}</form><h3>Secure NexOps access</h3><p>Firebase access is granted only when a verified Firebase account is bound to an active tenant membership. The Firebase UID itself is never editable here.</p><div className="nexcommand__directory">{data.access.map((member) => <article key={`${member.email}-${member.displayName}`}><h3>{member.displayName}</h3><p>{member.email ?? "No email"} · {member.role} · {member.active ? "Active" : "Inactive"}</p><p>{member.firebaseUidBound ? "Verified Firebase identity bound" : "No Firebase identity bound"}</p></article>)}</div>{message ? <p className="nexcommand__notice">{message}</p> : null}</section>;
}
function ContactFields({ prefix, contact }: { prefix: string; contact?: Record<string, unknown> }): React.ReactElement { const value = (key: string) => String(contact?.[key] ?? ""); return <div className="tenant-profile__grid"><label>Name<input name={`${prefix}Name`} defaultValue={value("name")} /></label><label>Title<input name={`${prefix}Title`} defaultValue={value("title")} /></label><label>Email<input type="email" name={`${prefix}Email`} defaultValue={value("email")} /></label><label>Phone<input name={`${prefix}Phone`} defaultValue={value("phone")} /></label></div>; }
function AddressFields({ prefix, address }: { prefix: string; address?: Record<string, unknown> }): React.ReactElement { const value = (key: string) => String(address?.[key] ?? ""); return <div className="tenant-profile__grid"><label>Street<input name={`${prefix}Street1`} defaultValue={value("street1")} /></label><label>Unit / suite<input name={`${prefix}Street2`} defaultValue={value("street2")} /></label><label>City<input name={`${prefix}City`} defaultValue={value("city")} /></label><label>State / province<input name={`${prefix}Province`} defaultValue={value("province")} /></label><label>Postal code<input name={`${prefix}PostalCode`} defaultValue={value("postalCode")} /></label><label>Country<input name={`${prefix}Country`} defaultValue={value("country")} /></label></div>; }
function addressFrom(form: FormData, prefix: string): Record<string, string> | undefined { const street1 = String(form.get(`${prefix}Street1`) ?? "").trim(); const city = String(form.get(`${prefix}City`) ?? "").trim(); const province = String(form.get(`${prefix}Province`) ?? "").trim(); const postalCode = String(form.get(`${prefix}PostalCode`) ?? "").trim(); const country = String(form.get(`${prefix}Country`) ?? "").trim(); if (![street1, city, province, postalCode, country].some(Boolean)) return undefined; return { street1, street2: String(form.get(`${prefix}Street2`) ?? "").trim(), city, province, postalCode, country }; }
