import React, { useEffect, useMemo, useState } from "react";
import type { User } from "firebase/auth";

type CommunicationTemplate = { id: string; category: string; label: string; description?: string; emailEnabled: boolean; smsEnabled: boolean; emailSubject?: string; emailBody?: string; smsBody?: string; };
type OnboardingTemplate = { id: string; flow: "tenant_onboarding" | "team_member_onboarding"; label: string; subject: string; body: string; };

async function request<T>(user: User, path: string, init?: RequestInit): Promise<T> {
  const token = await user.getIdToken();
  const response = await fetch(path, { ...init, headers: { authorization: `Bearer ${token}`, "content-type": "application/json", ...init?.headers } });
  const body = await response.json() as T & { ok?: boolean; error?: string };
  if (!response.ok || body.ok === false) throw new Error(body.error ?? "NexCommand template request failed.");
  return body;
}

function editorFields(template: CommunicationTemplate, onChange: (patch: Partial<CommunicationTemplate>) => void): React.ReactElement {
  return <><label>Email subject<input value={template.emailSubject ?? ""} onChange={(event) => onChange({ emailSubject: event.target.value })} /></label><label>Email body<textarea value={template.emailBody ?? ""} onChange={(event) => onChange({ emailBody: event.target.value })} /></label><label>SMS body<textarea value={template.smsBody ?? ""} onChange={(event) => onChange({ smsBody: event.target.value })} /></label><label><input type="checkbox" checked={template.emailEnabled} onChange={(event) => onChange({ emailEnabled: event.target.checked })} /> Email enabled</label><label><input type="checkbox" checked={template.smsEnabled} onChange={(event) => onChange({ smsEnabled: event.target.checked })} /> SMS enabled</label></>;
}

export function NexCommandCommunicationsTemplatesPanel(props: { user: User | null }): React.ReactElement {
  const [communications, setCommunications] = useState<CommunicationTemplate[]>([]);
  const [onboarding, setOnboarding] = useState<OnboardingTemplate[]>([]);
  const [selectedCategory, setSelectedCategory] = useState("");
  const [selectedFlow, setSelectedFlow] = useState<OnboardingTemplate["flow"]>("tenant_onboarding");
  const [status, setStatus] = useState("Loading NexCommand templates…");
  const [saving, setSaving] = useState(false);
  const [teamTenantId, setTeamTenantId] = useState("");
  const [teamEmail, setTeamEmail] = useState("");
  const [teamRole, setTeamRole] = useState<"OFFICE_ADMIN" | "TECHNICIAN">("TECHNICIAN");
  useEffect(() => { if (!props.user) return; void Promise.all([request<{ templates: CommunicationTemplate[] }>(props.user, "/api/platform/admin/templates/communications"), request<{ templates: OnboardingTemplate[] }>(props.user, "/api/platform/admin/templates/onboarding")]).then(([master, onboardingTemplates]) => { setCommunications(master.templates); setOnboarding(onboardingTemplates.templates); setSelectedCategory((current) => current || master.templates[0]?.category || ""); setStatus(""); }).catch((error: unknown) => setStatus(error instanceof Error ? error.message : "Templates are unavailable.")); }, [props.user]);
  const selected = useMemo(() => communications.find((template) => template.category === selectedCategory) ?? null, [communications, selectedCategory]);
  const selectedOnboarding = useMemo(() => onboarding.find((template) => template.flow === selectedFlow) ?? null, [onboarding, selectedFlow]);
  const patchSelected = (patch: Partial<CommunicationTemplate>) => setCommunications((current) => current.map((template) => template.category === selectedCategory ? { ...template, ...patch } : template));
  const patchOnboarding = (patch: Partial<OnboardingTemplate>) => setOnboarding((current) => current.map((template) => template.flow === selectedFlow ? { ...template, ...patch } : template));
  async function saveCommunication(): Promise<void> { if (!props.user || !selected) return; setSaving(true); try { await request(props.user, `/api/platform/admin/templates/communications/${encodeURIComponent(selected.category)}`, { method: "PUT", body: JSON.stringify({ label: selected.label, description: selected.description, emailEnabled: selected.emailEnabled, smsEnabled: selected.smsEnabled, emailSubject: selected.emailSubject, emailBody: selected.emailBody, smsBody: selected.smsBody }) }); setStatus(`${selected.label} saved as the NexCommand default.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Template save failed."); } finally { setSaving(false); } }
  async function saveOnboarding(): Promise<void> { if (!props.user || !selectedOnboarding) return; setSaving(true); try { await request(props.user, `/api/platform/admin/templates/onboarding/${selectedOnboarding.flow}`, { method: "PUT", body: JSON.stringify({ label: selectedOnboarding.label, subject: selectedOnboarding.subject, body: selectedOnboarding.body }) }); setStatus(`${selectedOnboarding.label} saved.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Template save failed."); } finally { setSaving(false); } }
  async function onboardTeamMember(event: React.FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!props.user) return; setSaving(true); try { await request(props.user, `/api/platform/admin/tenants/${encodeURIComponent(teamTenantId)}/team-onboarding`, { method: "POST", body: JSON.stringify({ email: teamEmail, role: teamRole }) }); setTeamEmail(""); setStatus("Team-member onboarding invitation accepted by the configured provider."); } catch (error) { setStatus(error instanceof Error ? error.message : "Team-member onboarding failed."); } finally { setSaving(false); } }
  return <section className="nexcommand__panel nexcommand__communications-templates"><p className="ui-eyebrow">NexCommand-owned content</p><h2>Master communications templates</h2><p>These 22 defaults copy into new tenants and are never directly visible to tenant accounts.</p>{status ? <p role="status">{status}</p> : null}<div className="nexcommand__template-editor"><aside>{communications.map((template) => <button key={template.category} className={template.category === selectedCategory ? "is-active" : ""} onClick={() => setSelectedCategory(template.category)}>{template.label}<small>{template.emailEnabled ? "Email" : ""}{template.smsEnabled ? " · SMS" : ""}</small></button>)}</aside>{selected ? <form onSubmit={(event) => { event.preventDefault(); void saveCommunication(); }}><h3>{selected.label}</h3><p>{selected.description}</p>{editorFields(selected, patchSelected)}<button disabled={saving}>{saving ? "Saving…" : "Save master template"}</button></form> : null}</div><h2>Onboarding templates</h2><p>These are NexCommand-only flows, separate from tenant communications.</p><div className="nexcommand__template-editor"><aside>{onboarding.map((template) => <button key={template.flow} className={template.flow === selectedFlow ? "is-active" : ""} onClick={() => setSelectedFlow(template.flow)}>{template.label}</button>)}</aside>{selectedOnboarding ? <form onSubmit={(event) => { event.preventDefault(); void saveOnboarding(); }}><h3>{selectedOnboarding.label}</h3><label>Subject<input value={selectedOnboarding.subject} onChange={(event) => patchOnboarding({ subject: event.target.value })} /></label><label>Body<textarea value={selectedOnboarding.body} onChange={(event) => patchOnboarding({ body: event.target.value })} /></label><button disabled={saving}>{saving ? "Saving…" : "Save onboarding template"}</button></form> : null}</div><form className="nexcommand__team-onboarding" onSubmit={(event) => void onboardTeamMember(event)}><h3>Onboard a tenant team member</h3><p>Uses the NexCommand team-member template and the existing Firebase credentials rail.</p><label>Tenant ID<input value={teamTenantId} onChange={(event) => setTeamTenantId(event.target.value)} required /></label><label>Email<input type="email" value={teamEmail} onChange={(event) => setTeamEmail(event.target.value)} required /></label><label>Role<select value={teamRole} onChange={(event) => setTeamRole(event.target.value as "OFFICE_ADMIN" | "TECHNICIAN")}><option value="TECHNICIAN">Technician</option><option value="OFFICE_ADMIN">Office Admin</option></select></label><button disabled={saving}>{saving ? "Sending…" : "Send NexCommand onboarding"}</button></form></section>;
}
