import React, { useEffect, useMemo, useState } from "react";
import type { User } from "firebase/auth";
import { getMyPlatformProfile, getPlatformTeam, saveMyPlatformProfile, setPlatformTeamUserStatus, type PlatformRole, type PlatformTeamUser, updatePlatformTeamUser } from "../api/nexCommandAdminApi";

const roles: PlatformRole[] = ["Owner", "Super Admin", "Administrator", "Developer", "Developer Admin", "Support", "Sales & Onboarding", "Marketing", "Finance", "Read Only"];
const roleSummaries: Record<PlatformRole, string> = {
  Owner: "All platform controls, including ownership and production authorization.", "Super Admin": "All controls except production and ownership transfer.", Administrator: "Tenant, support, onboarding, and platform operations.", Developer: "Read-only code, module, integration, and release visibility.", "Developer Admin": "Developer access plus module, integration, and release management.", Support: "Tenant visibility and support-case operations.", "Sales & Onboarding": "Prospects, onboarding work, and tenant visibility.", Marketing: "Prospect and usage visibility.", Finance: "Tenant, billing, and usage visibility.", "Read Only": "Personal profile and dashboard visibility only."
};

export function PlatformSettingsPanel({ user }: { user: User | null }): React.ReactElement {
  const [me, setMe] = useState<PlatformTeamUser | null>(null); const [team, setTeam] = useState<PlatformTeamUser[]>([]); const [status, setStatus] = useState("Loading platform settings…"); const [query, setQuery] = useState(""); const [roleFilter, setRoleFilter] = useState("ALL"); const [busy, setBusy] = useState("");
  const reload = async (): Promise<void> => { if (!user) return; try { const [profile, members] = await Promise.all([getMyPlatformProfile(user), getPlatformTeam(user)]); setMe(profile); setTeam(members); setStatus(""); } catch { setStatus("Settings are unavailable to this signed-in operator."); } };
  useEffect(() => { void reload(); }, [user]);
  const visible = useMemo(() => team.filter((member) => (roleFilter === "ALL" || member.role === roleFilter) && `${member.firstName} ${member.lastName} ${member.role}`.toLowerCase().includes(query.toLowerCase())), [team, query, roleFilter]);
  const saveProfile = async (event: React.FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); if (!user || !me) return; const data = new FormData(event.currentTarget); const identity = me.role === "Owner" ? { firstName: me.firstName, lastName: me.lastName, email: me.email ?? "" } : { firstName: String(data.get("firstName") ?? ""), lastName: String(data.get("lastName") ?? ""), email: String(data.get("email") ?? "") }; try { setBusy("profile"); setMe(await saveMyPlatformProfile(user, { ...identity, telephone: String(data.get("telephone") ?? "") || undefined, profilePhotoRef: String(data.get("profilePhotoRef") ?? me.profilePhotoRef) })); setStatus("Profile saved."); } catch { setStatus("Profile could not be saved."); } finally { setBusy(""); } };
  const changeRole = async (member: PlatformTeamUser, role: PlatformRole): Promise<void> => { if (!user || role === member.role || !window.confirm(`Change ${member.firstName} ${member.lastName} to ${role}?`)) return; try { setBusy(member.id); await updatePlatformTeamUser(user, member.id, { role }); await reload(); } catch { setStatus("Role update could not be saved."); } finally { setBusy(""); } };
  const changeStatus = async (member: PlatformTeamUser): Promise<void> => { if (!user || !window.confirm(`${member.accountStatus === "ACTIVE" ? "Disable" : "Reactivate"} ${member.firstName} ${member.lastName}?`)) return; try { setBusy(member.id); await setPlatformTeamUserStatus(user, member.id, member.accountStatus !== "ACTIVE"); await reload(); } catch { setStatus("Account status could not be updated."); } finally { setBusy(""); } };
  return <section className="nexcommand__panel nexcommand__settings"><p className="ui-eyebrow">Platform identity and access</p><h2>Settings, profile &amp; team roles</h2><p>Platform profiles are isolated from tenant users. No identity, invitation, or email is created from this screen.</p>{status ? <p className="nexcommand__notice" role="status">{status}</p> : null}{me ? <form className="nexcommand__form" onSubmit={(event) => void saveProfile(event)}><h3>My profile</h3><label>First name<input name="firstName" defaultValue={me.firstName} required /></label><label>Last name<input name="lastName" defaultValue={me.lastName} required /></label><label>Email<input name="email" type="email" defaultValue={me.email ?? ""} required /></label><p>Your role: <strong>{me.role}</strong>. Role and permission changes require managed-team authority.</p><button disabled={busy === "profile"}>{busy === "profile" ? "Saving…" : "Save profile"}</button></form> : null}<div className="nexcommand__filters"><label>Find team member<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name or role" /></label><label>Role<select value={roleFilter} onChange={(event) => setRoleFilter(event.target.value)}><option value="ALL">All roles</option>{roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></label></div><div className="nexcommand__team-grid">{visible.map((member) => <article key={member.id}><div><strong>{member.firstName} {member.lastName}</strong><span>{member.accountStatus}</span></div><label>Role<select value={member.role} disabled={busy === member.id} onChange={(event) => void changeRole(member, event.target.value as PlatformRole)}>{roles.map((role) => <option key={role} value={role}>{role}</option>)}</select></label><button type="button" disabled={busy === member.id} onClick={() => void changeStatus(member)}>{member.accountStatus === "ACTIVE" ? "Disable" : "Reactivate"}</button></article>)}</div><h3>Role access guide</h3><div className="nexcommand__role-guide">{roles.map((role) => <article key={role}><strong>{role}</strong><span>{roleSummaries[role]}</span></article>)}</div></section>;
}
