import React, { useEffect, useMemo, useState } from "react";
import type { User } from "firebase/auth";

interface Migration { id: string; tenantId: string; sourceSystem: string; scope: string; classification?: string; status: string; expectedRecords?: number; importedRecords?: number; rejectedRecords?: number; conflictOrDuplicateRecords?: number; launchImpact?: string; updatedAt: string; tenant?: { name: string } | null; }
export function PlatformMigrationsPanel({ user }: { user: User | null }): React.ReactElement {
  const [migrations, setMigrations] = useState<Migration[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (!user) return; void user.getIdToken().then((token) => fetch("/api/platform/admin/migrations", { headers: { authorization: `Bearer ${token}` } })).then(async (response) => { const body = await response.json() as { migrations?: Migration[] }; if (!response.ok) throw new Error(); setMigrations(body.migrations ?? []); }).catch(() => setError("Data query needs attention. NexTeam has logged the issue.")); }, [user]);
  const visible = useMemo(() => migrations.filter((migration) => `${migration.tenant?.name ?? ""} ${migration.tenantId} ${migration.sourceSystem}`.toLowerCase().includes(query.toLowerCase())), [migrations, query]);
  return <section className="nexcommand__panel"><p className="ui-eyebrow">Migration Tracking</p><h2>Migrations</h2><p>Tenant-linked migration records only. Tenant Blockers and Support are managed in Support Operations.</p><label>Search <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tenant, Tenant ID, or Source System" /></label><div className="nexcommand__directory">{visible.map((migration) => <article key={migration.id}><h3>{migration.tenant?.name ?? migration.tenantId}</h3><dl className="nexcommand__facts"><div><dt>Tenant ID</dt><dd>{migration.tenantId}</dd></div><div><dt>Source System</dt><dd>{migration.sourceSystem}</dd></div><div><dt>Migration Scope</dt><dd>{migration.scope}</dd></div><div><dt>Classification</dt><dd>{migration.classification ?? "Needs Review"}</dd></div><div><dt>Status</dt><dd>{migration.status}</dd></div><div><dt>Expected Records</dt><dd>{migration.expectedRecords ?? "Not Recorded"}</dd></div><div><dt>Imported</dt><dd>{migration.importedRecords ?? 0}</dd></div><div><dt>Rejected</dt><dd>{migration.rejectedRecords ?? 0}</dd></div><div><dt>Conflicts/Duplicates</dt><dd>{migration.conflictOrDuplicateRecords ?? 0}</dd></div><div><dt>Migration Progress</dt><dd>{migration.expectedRecords ? `${Math.min(100, Math.round(((migration.importedRecords ?? 0) / migration.expectedRecords) * 100))}%` : "Not Recorded"}</dd></div><div><dt>Last Activity</dt><dd>{migration.updatedAt}</dd></div><div><dt>Launch Impact</dt><dd>{migration.launchImpact ?? "Watch"}</dd></div></dl></article>)}{!visible.length ? <p>No tenant migration records exist for this search.</p> : null}</div>{error ? <p className="nexcommand__notice">{error}</p> : null}</section>;
}
