import React, { useEffect, useState } from "react";
import type { User } from "firebase/auth";

type Blocker = { id: string; tenantId: string; title: string; detail: string; severity: string; status: string };
type Escalation = { id: string; blockerId: string; priority: string; status: string; summary: string };
async function request<T>(user: User, path: string, init?: RequestInit): Promise<T> { const token = await user.getIdToken(); const response = await fetch(path, { ...init, headers: { authorization: `Bearer ${token}`, "content-type": "application/json", ...init?.headers } }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error || "Support request failed."); return body; }
export function PlatformSupportPanel({ user }: { user: User | null }): React.ReactElement {
  const [tenantId, setTenantId] = useState(""); const [title, setTitle] = useState(""); const [detail, setDetail] = useState(""); const [blockers, setBlockers] = useState<Blocker[]>([]); const [escalations, setEscalations] = useState<Escalation[]>([]); const [message, setMessage] = useState("");
  const reload = async (): Promise<void> => { if (!user) return; const query = tenantId.trim() ? `?tenantId=${encodeURIComponent(tenantId.trim())}` : ""; const result = await request<{ blockers: Blocker[]; escalations: Escalation[] }>(user, `/api/platform/admin/tenant-blockers${query}`); setBlockers(result.blockers); setEscalations(result.escalations); };
  useEffect(() => { void reload().catch(() => setMessage("Data query needs attention. NexTeam has logged the issue.")); }, [user, tenantId]);
  const save = async (event: React.FormEvent<HTMLFormElement>): Promise<void> => { event.preventDefault(); if (!user) return; try { await request(user, `/api/platform/admin/tenants/${encodeURIComponent(tenantId)}/blockers`, { method: "POST", body: JSON.stringify({ title, detail, category: "CONFIGURATION", severity: "BLOCKING" }) }); setTitle(""); setDetail(""); setMessage("Tenant Blocker Saved."); await reload(); } catch { setMessage("Data query needs attention. NexTeam has logged the issue."); } };
  return <section className="nexcommand__panel"><p className="ui-eyebrow">Support Operations</p><h2>Tenant Blockers and Support</h2><p>Migrations are managed separately in Migration Tracking.</p><form onSubmit={(event) => void save(event)}><label>Tenant ID<input required value={tenantId} onChange={(event) => setTenantId(event.target.value)} /></label><label>Blocker Title<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Detail<textarea required value={detail} onChange={(event) => setDetail(event.target.value)} /></label><button type="submit">Save Blocker</button></form><div className="nexcommand__directory">{blockers.map((blocker) => <article key={blocker.id}><h3>{blocker.title}</h3><p>{blocker.detail}</p><span>{blocker.tenantId} · {blocker.severity} · {blocker.status}</span></article>)}{escalations.map((escalation) => <article key={escalation.id}><h3>Support {escalation.priority}</h3><p>{escalation.summary}</p><span>{escalation.status}</span></article>)}</div>{message ? <p className="nexcommand__notice">{message}</p> : null}</section>;
}
