#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

function fail(message) {
  console.error(message);
  process.exit(1);
}

function readInput(filePath) {
  if (!filePath) fail('Usage: node scripts/planner-helper.js <input.md> <output.md>');
  if (!fs.existsSync(filePath)) fail(`Input file not found: ${filePath}`);
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');
}

function extractSection(text, heading) {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const regex = new RegExp(`^##\\s+${escaped}\\s*\\n([\\s\\S]*?)(?=^##\\s+|$)`, 'm');
  const match = text.match(regex);
  return match ? match[1].trim() : '';
}

function extractBullets(sectionText) {
  return sectionText
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith('- '))
    .map((line) => line.slice(2).trim());
}

function firstNonEmptyLine(sectionText) {
  const lines = sectionText
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  return lines[0] || '[Needs clarification]';
}

function detectWorkType(text) {
  const lower = text.toLowerCase();
  if (lower.includes('workflow')) return 'workflow change';
  if (lower.includes('bug')) return 'bug fix';
  if (lower.includes('documentation')) return 'documentation update';
  if (lower.includes('feature')) return 'feature implementation';
  if (lower.includes('agent')) return 'agent/workflow definition';
  return '[Needs clarification]';
}

function unique(items) {
  return [...new Set(items)];
}

function bulletList(items) {
  return items.map((item) => `- ${item}`).join('\n');
}

function buildPlan(text) {
  const requestName = firstNonEmptyLine(extractSection(text, '1. Requested Agent Name'));
  const domain = firstNonEmptyLine(extractSection(text, '2. Requested Domain'));
  const mission = firstNonEmptyLine(extractSection(text, '3. Mission'));
  const mainTasks = extractBullets(extractSection(text, '4. Main Tasks'));
  const inputs = extractBullets(extractSection(text, '5. Inputs'));
  const allowedTools = extractBullets(extractSection(text, '7. Allowed Tools'));
  const stopConditions = extractBullets(extractSection(text, '11. Stop Conditions'));
  const notes = extractBullets(extractSection(text, '13. Notes / Constraints'));
  const ambiguityFlags = extractBullets(extractSection(text, 'Ambiguity Flags'));

  const workType = detectWorkType(text);

  const suggestedSteps = unique([
    `confirm scope for "${requestName}"`,
    'review the structured request with a human before execution',
    ...mainTasks.map((task) => `translate task into one practical work item: ${task}`),
    'identify the smallest implementation or documentation slice',
    'prepare a diff for human review before commit',
  ]);

  const risks = unique([
    ...ambiguityFlags,
    inputs.includes('[Needs clarification]') ? 'Required input details are incomplete.' : null,
    stopConditions.some((item) => item.includes('required context is missing')) ? 'Execution can stall if required context is not supplied.' : null,
  ].filter(Boolean));

  const dependencies = unique([
    domain !== '[Needs clarification]' ? `Domain context: ${domain}` : 'Domain context: [Needs clarification]',
    ...allowedTools.map((tool) => `Reference: ${tool}`),
    ...inputs.map((input) => `Input: ${input}`),
  ]);

  const reviewNeeded = [
    'Confirm the request summary and scope are correct.',
    'Approve the suggested steps before implementation.',
    'Resolve all [Needs clarification] placeholders before broader execution.',
  ];

  const planNotes = unique([
    ...notes,
    'Human review is still required before this plan is acted on.',
    'This output is a simple planning aid, not an approval or execution system.',
  ]);

  return `# IMPLEMENTATION_PLAN_DRAFT.md
> Generated by scripts/planner-helper.js from a structured request. Human review is still required.

## Request Summary
${requestName}: ${mission}

## Recommended Work Type
${workType}

## Suggested Steps
${bulletList(suggestedSteps)}

## Risks / Blockers
${bulletList(risks.length ? risks : ['No major blocker detected, but human review is still required.'])}

## Dependencies / Inputs Needed
${bulletList(dependencies)}

## Human Review Needed
${bulletList(reviewNeeded)}

## Notes
${bulletList(planNotes)}
`;
}

function main() {
  const inputPath = process.argv[2];
  const outputPath = process.argv[3];

  if (!inputPath || !outputPath) {
    fail('Usage: node scripts/planner-helper.js <input.md> <output.md>');
  }

  const input = readInput(inputPath);
  const output = buildPlan(input);
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output, 'utf8');
  console.log(`Wrote implementation plan draft to ${outputPath}`);
}

main();
