import type { Request, Response } from "express";
import type { CrmRouteContext } from "../../runtime/routeRuntime.js";
import { createCompensationFactInputSchema, createLaborFactInputSchema, payrollExportInputSchema, voidTimePayFactInputSchema } from "./timePayFoundation.js";

export function registerTimePayRoutes(context: CrmRouteContext): void {
  const { app, defaultTenantId, env, requireBillingAccess, sendRouteError, timePayService } = context;
  const tenantFrom = (req: Request) => typeof req.query.tenantId === "string" && req.query.tenantId.trim() ? req.query.tenantId : (typeof req.body?.tenantId === "string" && req.body.tenantId.trim() ? req.body.tenantId : defaultTenantId(env));
  app.get("/api/crm/time-pay/labor", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "listLaborFacts"); const employeeId = typeof req.query.employeeId === "string" ? req.query.employeeId : undefined; res.json({ ok: true, tenantId, actorRole: access.role, laborFacts: await timePayService().listLabor(tenantId, employeeId) }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/time-pay/labor", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "createLaborFact"); const fact = await timePayService().createLabor(createLaborFactInputSchema.parse({ ...req.body, tenantId }), access.tenantUserId); res.status(201).json({ ok: true, tenantId, actorRole: access.role, laborFact: fact }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/time-pay/labor/:id/void", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "voidLaborFact"); const fact = await timePayService().voidLabor(tenantId, req.params.id ?? "", voidTimePayFactInputSchema.parse(req.body), access.tenantUserId); res.json({ ok: true, tenantId, actorRole: access.role, laborFact: fact }); } catch (error) { sendRouteError(res, error); } });
  app.get("/api/crm/time-pay/compensation", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "listCompensationFacts"); const employeeId = typeof req.query.employeeId === "string" ? req.query.employeeId : undefined; res.json({ ok: true, tenantId, actorRole: access.role, compensationFacts: await timePayService().listCompensation(tenantId, employeeId) }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/time-pay/compensation", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "createCompensationFact"); const fact = await timePayService().createCompensation(createCompensationFactInputSchema.parse({ ...req.body, tenantId }), access.tenantUserId); res.status(201).json({ ok: true, tenantId, actorRole: access.role, compensationFact: fact }); } catch (error) { sendRouteError(res, error); } });
  app.post("/api/crm/time-pay/compensation/:id/void", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "voidCompensationFact"); const fact = await timePayService().voidCompensation(tenantId, req.params.id ?? "", voidTimePayFactInputSchema.parse(req.body), access.tenantUserId); res.json({ ok: true, tenantId, actorRole: access.role, compensationFact: fact }); } catch (error) { sendRouteError(res, error); } });
  app.get("/api/crm/time-pay/payroll-draft", async (req: Request, res: Response) => { try { const tenantId = tenantFrom(req); const access = await requireBillingAccess(req, tenantId, "exportPayrollDraft"); const draft = await timePayService().payrollDraft(tenantId, payrollExportInputSchema.parse(req.query)); res.json({ ok: true, tenantId, actorRole: access.role, payrollDraft: draft }); } catch (error) { sendRouteError(res, error); } });
}
