import type { CommunicationTemplate, LifecycleCommandContract } from "@nexteam/core";
import { PORTAL_AUTHORIZATION_PROFILE_ID } from "../../../../nexops/shared/lifecycle/policy.js";

export const PORTAL_CORE_COMMANDS: LifecycleCommandContract[] = [
  {
    commandId: "portal.request_reschedule",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "future_visit_exists", when: "customer is requesting a future appointment change" }],
    dominantLabel: "Request reschedule",
    secondaryActions: ["Request cancellation"],
    requiredFields: ["requestedWindow", "reason"],
    blockingConditions: [],
    transitionResult: "Creates ClientScheduleRequest while leaving the visit schedule unchanged.",
    createdEntities: ["ClientScheduleRequest"],
    sideEffects: [{ kind: "notification", detail: "create_schedule_request_attention" }, { kind: "audit", detail: "client_schedule_request.created" }],
    communicationTriggers: [],
    auditEvent: "client_schedule_request.created",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Portal requests require live token validation." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "One client schedule request per portal submit." },
    policyDependencies: ["D17"]
  },
  {
    commandId: "portal.request_cancellation",
    type: "command",
    actorSurface: "portal",
    authorizationProfileId: PORTAL_AUTHORIZATION_PROFILE_ID,
    currentConditions: [{ code: "future_visit_exists", when: "customer is requesting cancelation rather than reschedule" }],
    dominantLabel: "Request cancellation",
    secondaryActions: ["Request reschedule"],
    requiredFields: ["reason"],
    blockingConditions: [],
    transitionResult: "Creates ClientScheduleRequest while leaving the current visit schedule unchanged until staff acts.",
    createdEntities: ["ClientScheduleRequest"],
    sideEffects: [{ kind: "notification", detail: "create_schedule_request_attention" }, { kind: "audit", detail: "client_schedule_request.created" }],
    communicationTriggers: [],
    auditEvent: "client_schedule_request.created",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Portal requests require live token validation." },
    idempotencyScope: { keys: ["tenantId", "visitId", "clientOperationId"], description: "One client schedule request per portal submit." },
    policyDependencies: ["D17"]
  },
  {
    commandId: "client_schedule_request.accept_reschedule",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "visit.reschedule",
    currentConditions: [{ code: "request_pending", when: "staff is resolving a pending reschedule request" }],
    dominantLabel: "Accept reschedule",
    secondaryActions: ["Decline", "Counter-propose"],
    requiredFields: ["visitStart", "visitEnd"],
    blockingConditions: [{ code: "availability_conflict", when: "requested or proposed window is unavailable", blockerCopy: "That requested window is not available for the assigned crew." }],
    transitionResult: "Resolves the request as accepted and executes the actual visit.reschedule command.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "schedule_request_resolution" }, { kind: "audit", detail: "client_schedule_request.accepted" }],
    communicationTriggers: [{ templateId: "schedule_request_resolution", mode: "auto" }],
    auditEvent: "client_schedule_request.accepted",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Resolution is online only." },
    idempotencyScope: { keys: ["tenantId", "scheduleRequestId", "clientOperationId"], description: "One accept decision per request." },
    policyDependencies: ["D17"]
  },
  {
    commandId: "client_schedule_request.accept_cancellation",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "visit.cancel",
    currentConditions: [{ code: "request_pending", when: "staff is resolving a pending cancellation request" }],
    dominantLabel: "Accept cancellation",
    secondaryActions: ["Decline", "Counter-propose"],
    requiredFields: ["reason"],
    blockingConditions: [],
    transitionResult: "Resolves the request as accepted and executes visit.cancel without auto-applying before the staff decision.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "schedule_request_resolution" }, { kind: "audit", detail: "client_schedule_request.accepted" }],
    communicationTriggers: [{ templateId: "schedule_request_resolution", mode: "auto" }],
    auditEvent: "client_schedule_request.accepted",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Resolution is online only." },
    idempotencyScope: { keys: ["tenantId", "scheduleRequestId", "clientOperationId"], description: "One accept decision per request." },
    policyDependencies: ["D17"]
  },
  {
    commandId: "client_schedule_request.decline",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "schedule_request.manage",
    currentConditions: [{ code: "request_pending", when: "staff is declining the client's requested change" }],
    dominantLabel: "Decline request",
    secondaryActions: ["Accept request", "Counter-propose"],
    requiredFields: ["resolutionNote"],
    blockingConditions: [],
    transitionResult: "Resolves the schedule request as declined without changing the current visit schedule.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "schedule_request_resolution" }, { kind: "audit", detail: "client_schedule_request.declined" }],
    communicationTriggers: [{ templateId: "schedule_request_resolution", mode: "auto" }],
    auditEvent: "client_schedule_request.declined",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Resolution is online only." },
    idempotencyScope: { keys: ["tenantId", "scheduleRequestId", "clientOperationId"], description: "One decline decision per request." },
    policyDependencies: ["D17"]
  },
  {
    commandId: "client_schedule_request.counter_propose",
    type: "command",
    actorSurface: "office_web",
    requiredPermission: "schedule_request.manage",
    currentConditions: [{ code: "request_pending", when: "staff needs to offer a different window" }],
    dominantLabel: "Counter-propose",
    secondaryActions: ["Accept request", "Decline"],
    requiredFields: ["proposedWindow", "resolutionNote"],
    blockingConditions: [],
    transitionResult: "Resolves the schedule request as counter_proposed and notifies the customer without changing the schedule yet.",
    createdEntities: [],
    sideEffects: [{ kind: "communication", detail: "schedule_request_resolution" }, { kind: "audit", detail: "client_schedule_request.counter_proposed" }],
    communicationTriggers: [{ templateId: "schedule_request_resolution", mode: "auto" }],
    auditEvent: "client_schedule_request.counter_proposed",
    confirmationTier: "standard",
    offlineBehavior: { supported: false, behavior: "Resolution is online only." },
    idempotencyScope: { keys: ["tenantId", "scheduleRequestId", "clientOperationId"], description: "One counter-proposal per request resolution action." },
    policyDependencies: ["D17"]
  }
];

export const PORTAL_CORE_COMMUNICATIONS: CommunicationTemplate[] = [
  {
    templateId: "delivery_failure",
    trigger: "any_send_command.failure",
    channels: ["internal"],
    mode: "auto",
    recipientResolution: "Route to owner and office-admin alert channels for the tenant.",
    previewRequired: false,
    suppressionRule: "Never suppress when customer delivery failed.",
    idempotencyScope: "delivery.failure:{entityType}:{entityId}:{attemptId}",
    failureBehavior: "Create a follow-up task and surface the failure in the Home needs-attention zone.",
    auditEvent: "delivery.failure_alerted",
    attachmentPolicy: "No customer attachments."
  },
  {
    templateId: "schedule_request_resolution",
    trigger: "client_schedule_request.resolve",
    channels: ["email", "sms"],
    mode: "auto",
    recipientResolution: "Use the client schedule request submitter contact.",
    previewRequired: false,
    suppressionRule: "Suppress only when the specific channel is unavailable.",
    idempotencyScope: "schedule_request.resolution:{scheduleRequestId}:{status}",
    failureBehavior: "Keep the staff decision and create an internal retry task.",
    auditEvent: "schedule_request.resolution_sent",
    attachmentPolicy: "No attachments."
  }
];
